//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajaArticulo
    {
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Cantidad { get; set; }
        public string Observacion { get; set; }
        public long MotivoBajaId { get; set; }
        public long ArticuloId { get; set; }
    
        public virtual MotivoBaja MotivoBaja { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
