//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPagoCheque : FormaPago
    {
        public long BancoId { get; set; }
        public string Numero { get; set; }
        public string EnteEmisor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int Dias { get; set; }
    
        public virtual Banco Banco { get; set; }
    }
}
