//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPagoTarjeta : FormaPago
    {
        public long PlanTarjetaId { get; set; }
        public string Cupon { get; set; }
        public string Numero { get; set; }
        public string NumeroTarjeta { get; set; }
    
        public virtual PlanTarjeta PlanTarjeta { get; set; }
    }
}
