//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloXCommerceContainer : DbContext
    {
        public ModeloXCommerceContainer()
            : base("name=ModeloXCommerceContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Direccion> Direcciones { get; set; }
        public virtual DbSet<Localidad> Localidades { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Rubro> Rubros { get; set; }
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<MotivoBaja> MotivosBajas { get; set; }
        public virtual DbSet<BajaArticulo> BajaArticulos { get; set; }
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<DetalleCaja> DetalleCajas { get; set; }
        public virtual DbSet<ListaPrecio> ListaPrecios { get; set; }
        public virtual DbSet<Precio> Precios { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<CondicionIva> CondicionIvas { get; set; }
        public virtual DbSet<Salon> Salones { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Comprobante> Comprobantes { get; set; }
        public virtual DbSet<DetalleComprobante> DetalleComprobantes { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<FormaPago> FormasPagos { get; set; }
        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<Tarjeta> TarjetaSet { get; set; }
        public virtual DbSet<PlanTarjeta> PlanesTarjetas { get; set; }
        public virtual DbSet<Proveedor> Proveedores { get; set; }
    }
}
